### ISSUE TITLE
კონკურსებისათვის კალენდრის მოფიქრება

### ISSUE THREAD

**Issue by Zhestokus** [CITI-EVO/GMUS#32]
ეს ნაწილი გასავლელია, გასარკვევია უფრო დეტალებსჰი რა იგულისხმება და როგორ გაკეტდეს

**Comment by Zhestokus** [comment]
ფორმაზე დაემატოს Visibility Expression რომლის საშუალებითაც ადმინს შეეძლება მიუთითოს პირობები თუ რა შემთზვევაში უნდა ჩანდეს ფორმა (მაგალითად მიუთითოს პერიოდი)

**Comment by gino4nx** [comment]
DONE
